version: '3.8'
services:
  app-builder:
    build: 
      context: ./
    command: npm run dev
    volumes:
      - .:/usr/app-builder/
      - /usr/app-builder/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development